### PR TITLE
Deploy premint v2 to zora goerli and zora sepolia.  Simulate and give instruactions for premint upgrades

### PR DESCRIPTION
**Pull request by oveddan**
* updated deployment scripts to not fail if deploying preminter, and its determinstic address is already taken; this means the preminter has already been created, and it now continues gracefully.
* deployed 2.5.1 to zora sepolia and zora goerli, and upgraded preminter proxy
* updated upgrade simulation tests to simulate and pending premint upgrades and print necessary calldata

we now can get this output in tests:

Screenshot 2023-11-20 at 7 09 35 PM

### CODE REVIEW

**Comment by oveddan** [comment]
Current dependencies on/for this PR:
* main
  * **PR #376** <a href="https://app.graphite.dev/github/pr/ourzora/zora-protocol/376?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #377** <a href="https://app.graphite.dev/github/pr/ourzora/zora-protocol/377?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #378** <a href="https://app.graphite.dev/github/pr/ourzora/zora-protocol/378?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/ourzora/zora-protocol/378?utm_source=stack-comment).

**Review by kulkarohan — DISMISSED** [review]

**Comment by kulkarohan** [comment]
lgtm! 

thoughts on moving all deploy-related files (eg. `ZoraDeployerBase`, `ZoraDeployerUtils`)  to `/script`?

**Comment by oveddan** [comment]
> lgtm!
> 
> thoughts on moving all deploy-related files (eg. `ZoraDeployerBase`, `ZoraDeployerUtils`) to `/script`?

i can see the need for that, but i feel they are more like classes than scrips, and everything in `/script` is meant for running the script file that is there (they're all `.s.sol` in there) so if those files are to be moved into there, they should be in a subfolder

**Comment by oveddan** [comment]
already approved, just approval got lost in rebase. merging.

**Pull request merged**
