### PR TITLE
New `protocol-deployments` package - separate versioning of contracts from publishing deployment updates

### PR DESCRIPTION
**Pull request by oveddan**
Created new package `protocol-deployments`

* deployment scripts for 1155 contracts have been moved from `1155-contracts` to this new package
* deployed 1155 contract addresses have been moved from `1155-contracts` to this new package.

Problem this solves:
* every time we deployed a contract and want to to publish the changes in a package we had to bump the contract version, since we require the package version to match the contract version.

With this change, we can version the contracts independently from the deployed addresses.

You can see this in action in the upstream branch "Deploy zora sepolia" where we deployed the contracts to the new Zora Sepolia chain, and just bumped the `protocol-deployments` version without needing to bump the `1155-contracts` version.

* The `1155-contracts` wagmi generator now just generates abis to bundle in the package json.
* The `protocol-deployments` wagmi generator imports the abis from `1155-contracts` and bundles them with the deployed addresses.
* `premint-sdk` imports from `protocol-deployments` to get contract abis and addresses from it

### CODE REVIEW

**Comment by oveddan** [comment]
Current dependencies on/for this PR:
* main
  * **PR #276** <a href="https://app.graphite.dev/github/pr/ourzora/zora-protocol/276" target="_blank">Graphite</a> 
    * **PR #304** <a href="https://app.graphite.dev/github/pr/ourzora/zora-protocol/304" target="_blank">Graphite</a> 
      * **PR #305** <a href="https://app.graphite.dev/github/pr/ourzora/zora-protocol/305" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ourzora/zora-protocol/305?utm_source=stack-comment).

**Review by oveddan — COMMENTED** [review]
todo:
* add readme to `protocol-deployments` with examples

**Comment by iainnash** [comment]
Would be great to create folders to separate the scripts. Given the complexity of the deployment what are your thoughts on creating different packages for each project deployments with a standard pattern?

**Comment by kulkarohan** [comment]
> Would be great to create folders to separate the scripts. Given the complexity of the deployment what are your thoughts on creating different packages for each project deployments with a standard pattern?

yeah maybe imports could be project specific ? eg`@zoralabs/protocol-deployments/1155-contracts`, `@zoralabs/protocol-deployments/721-contracts`

**Comment by oveddan** [comment]
### Merge activity

* **Nov 1, 5:27 PM**: @oveddan started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/ourzora/zora-protocol/305).

**Comment by oveddan** [comment]
> > Would be great to create folders to separate the scripts. Given the complexity of the deployment what are your thoughts on creating different packages for each project deployments with a standard pattern?
> 
> yeah maybe imports could be project specific ? eg`@zoralabs/protocol-deployments/1155-contracts`, `@zoralabs/protocol-deployments/721-contracts`

sounds good will do this in a v2

**Pull request merged**
